import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Card from '@/components/Card'
import { useEffect, useState } from 'react'

export default function Home() {
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [questions, setQuestions] = useState([]);
  const [answers, setAnswers] = useState([]);
  useEffect(() => {
    fetch('/api/questions')
      .then(res => res.json()) 
      .then(data => setQuestions(data))
      .catch(error => console.log(error));
  }, []);
  useEffect(() => {
    console.log(answers);
  }, [answers])

  const saveAnswer = (id) => {
    setAnswers((prev) => [
      ...prev,
      {
        questionID: currentQuestion,
        answerID: id
      }
    ])
  }

  const nextQuestion = (id) => {
    if (answers.length == currentQuestion+1) return;
    saveAnswer(id);
    if (questions.length - 1 <= currentQuestion) return;
    setCurrentQuestion((old) => old + 1);
  }

  if (questions.length == 0) {
    return <div>Loading...</div>
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Card next={nextQuestion} question={questions[currentQuestion]}/>
      </main>
    </>
  )
}
